In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"D:\ALL_PROJECT FOLDER\zomato\Zomato_delivery_project\artifact\data ingestion\train.csv")

In [3]:
df.head()

,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,RANCHIRES12DEL01,35.0,4.6,0.000000,0.000000,0.070000,0.070000,20-03-2022,17:15,17:30,Windy,Medium,1,Drinks,scooter,1.0,No,Metropolitian,26
1,RANCHIRES13DEL01,38.0,4.7,23.374989,85.335486,23.414989,85.375486,05-03-2022,13:30,13:40,Sandstorms,High,2,Buffet,motorcycle,1.0,No,Metropolitian,29
2,HYDRES07DEL02,36.0,4.8,17.424114,78.347554,17.554114,78.477554,08-03-2022,22:35,22:40,Stormy,Low,2,Drinks,electric_scooter,0.0,No,Urban,17
3,INDORES01DEL01,27.0,5.0,22.695207,75.866059,22.735207,75.906059,19-03-2022,16:35,16:40,Stormy,Medium,2,Drinks,motorcycle,0.0,No,Metropolitian,24
4,KOLRES20DEL03,38.0,4.7,22.514119,88.362504,22.604119,88.452504,18-02-2022,20:50,20:55,Cloudy,Jam,0,Snack,motorcycle,1.0,No,Metropolitian,46

In [6]:
df.dtypes

Delivery_person_ID              object
Delivery_person_Age            float64
Delivery_person_Ratings        float64
Restaurant_latitude            float64
Restaurant_longitude           float64
Delivery_location_latitude     float64
Delivery_location_longitude    float64
Order_Date                      object
Time_Orderd                     object
Time_Order_picked               object
Weather_conditions              object
Road_traffic_density            object
Vehicle_condition                int64
Type_of_order                   object
Type_of_vehicle                 object
multiple_deliveries            float64
Festival                        object
City                            object
Time_taken (min)                 int64
dtype: object

In [13]:
df["Vehicle_condition"].unique()

array([1, 2, 0, 3], dtype=int64)